import { StyleSheet } from 'react-native';

import Metrics from '../../themes/Metrics';
import Colors from '../../themes/Colors';

export default StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statusbar: {
    flex: 0,
    width: Metrics.screenWidth,
    height: Metrics.statusbarHeight,
    backgroundColor: Colors.statusbarBg,
  },
  navbar: {
    flex: 0,
    height: Metrics.navbarHeight,
    width: Metrics.screenWidth,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: Metrics.padding,
  },
  navTitle: {
    fontSize: 22,
    fontWeight: 'normal', 
    color: 'white',
    backgroundColor: 'transparent',
  },
  contentView: {
    flex: 1,
    width: Metrics.screenWidth,
    // alignItems: 'center'
    marginHorizontal: 20,
  },
  list: {
    flex: 1,
    width: Metrics.screenWidth,
    alignItems: 'center'
  },
  item: {
    width: Metrics.screenWidth / 2 - Metrics.padding,
    height: Metrics.screenWidth / 2 + 100,
    margin: Metrics.padding / 2, 
  },
  dropDownItem: {
    padding: 10,
    fontSize: 15,
  },
  filterUserInput: { 
    height: 36,
    width : (Metrics.screenWidth - 210)/2,
    fontSize: 16, 
    color: 'white', 
    backgroundColor: 'transparent', 
    fontWeight: 'bold', 
    paddingLeft: 5, 
    paddingRight: 5,
    borderColor: 'white',
    borderTopWidth: 1,
    borderLeftWidth: 1,
    borderBottomWidth: 1,
    borderRightWidth: 0,
    borderTopLeftRadius: 5,
    borderBottomLeftRadius: 5,
  },
  filterUserSelect: { 
    width: 40, 
    height: 35, 
    backgroundColor: 'transparent', 
    borderTopRightRadius: 5, 
    borderBottomRightRadius: 5, 
    borderWidth: 1, 
    borderColor: 'white'
  },
  filterDateInput: { 
    height: 36,
    fontSize: 16, 
    color: 'white', 
    backgroundColor: 'transparent', 
    fontWeight: 'bold',
    width: (Metrics.screenWidth - 210)/2,
    paddingLeft: 5, 
    paddingRight: 5,
    borderColor: 'white',
    borderTopWidth: 1,
    borderLeftWidth: 1,
    borderBottomWidth: 1,
    borderRightWidth: 0,
    borderTopLeftRadius: 5,
    borderBottomLeftRadius: 5,
  },
  filterDateSelect: { 
    width: 40, 
    height: 35, 
    backgroundColor: 'transparent', 
    borderTopRightRadius: 5, 
    borderBottomRightRadius: 5, 
    borderWidth: 1, 
    borderColor: 'white'
  },
  dateContainer : {
    marginTop: 20, 
    marginLeft: 20, 
    flexDirection: 'row',  
    width: Metrics.screenWidth - 110,
    
  },
  filterHouseInput: { 
    height: 36,
    width: Metrics.screenWidth - 150,
    fontSize: 16, 
    color: 'white', 
    backgroundColor: 'transparent', 
    fontWeight: 'bold',
    marginLeft: 20,
    paddingLeft: 5, 
    paddingRight: 5,
    borderColor: 'white',
    borderTopWidth: 1,
    borderLeftWidth: 1,
    borderBottomWidth: 1,
    borderRightWidth: 0,
    borderTopLeftRadius: 5,
    borderBottomLeftRadius: 5,
    
  },
  filterHouseSelect: { 
    borderWidth :1,
    borderColor : 'blue',
    width: 40, 
    height: 35, 
    backgroundColor: 'transparent', 
    borderTopRightRadius: 5, 
    borderBottomRightRadius: 5, 
    borderWidth: 1, 
    borderColor: 'white',
  },
  item_top: {
    justifyContent: 'space-between', 
    flexDirection: 'row', 
    paddingBottom: 5,
    paddingTop: 10,
  },
  line: { 
    justifyContent: 'space-between', 
    flexDirection: 'row', 
    borderBottomWidth: 1, 
    borderBottomColor: 'white',
    paddingBottom: 10,
    paddingTop: 5,
  },
  listUserItem: {
    paddingLeft: 5, 
    paddingRight: 5, 
    paddingTop: 10, 
    paddingBottom: 10, 
    width: 100,
    backgroundColor: 'rgba(52, 52, 52, 0.8)',
    borderBottomColor: 'white',
    borderBottomWidth: 1,
    borderLeftColor: 'white',
    borderLeftWidth: 1,
    borderRightColor: 'white',
    borderRightWidth: 1, 
  },
  listHouseItem: {
    paddingLeft: 5, 
    paddingRight: 5, 
    paddingTop: 10, 
    paddingBottom: 10, 
    width: 260,
    backgroundColor: 'rgba(52, 52, 52, 0.8)',
    borderBottomColor: 'white',
    borderBottomWidth: 1,
    borderLeftColor: 'white',
    borderLeftWidth: 1,
    borderRightColor: 'white',
    borderRightWidth: 1, 
  }
});